import CustomError from '@utils/customError';
import quizModel from '@models/quiz.model';
import * as AIService from './openAI.services';

export const generateQuestions = async ({
  userId,
  topicId,
  topicName,
  numQuestions,
}: {
  userId: string;
  topicId: string;
  topicName: string;
  numQuestions: number;
}) => {
  if (!topicId || !numQuestions || !userId) {
    throw new CustomError('Invalid input parameters', 400);
  }
  try {
    const questions = await AIService.generateQuestionsByAI(
      topicName,
      numQuestions
    );
    if (
      !questions ||
      !Array.isArray(questions.allQuestions) ||
      questions.allQuestions.length === 0
    ) {
      throw new CustomError('No questions generated by AI', 404);
    }
    const newQuiz = new quizModel({
      userId,
      topic: topicId,
      questions: questions.allQuestions,
    });
    await newQuiz.save();
    return { questions: questions.allQuestions };
  } catch (error: any) {
    console.error('Error generating questions:', error);
    throw new CustomError('Failed to generate questions', 500);
  }
};

export const getAllQuizzesByID = async ({ userId }: { userId: string }) => {
  try {
    const quizzes = await quizModel
      .find({ userId })
      .populate('userId', '-password');
    if (!quizzes || quizzes.length === 0) {
      throw new CustomError('No quizzes found', 404);
    }
    return quizzes;
  } catch (error: any) {
    console.error('Error fetching all quizzes:', error);
    throw new CustomError('Failed to fetch quizzes', 500);
  }
};

export const getQuizzesByTopicId = async ({ topicId }: { topicId: string }) => {
  if (!topicId) {
    throw new CustomError('Topic ID is required', 400);
  }
  try {
    const quizzes = await quizModel
      .find({ topic: topicId })
      .populate('userId', '-password');
    if (!quizzes || quizzes.length === 0) {
      throw new CustomError('No quizzes found for the given topic ID', 404);
    }
    return quizzes;
  } catch (error: any) {
    console.error('Error fetching quizzes by topic ID:', error);
    throw new CustomError('Failed to fetch quizzes', 500);
  }
};